image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - johnpapa.winteriscoming
    - vscode-icons-team.vscode-icons
    - esbenp.prettier-vscode
    - naumovs.color-highlight
    - dsznajder.es7-react-js-snippets
    - wakatime.vscode-wakatime
    - asciidoctor.asciidoctor-vscode

tasks:
  - name: Use Node 12.18.3
    init: |
      source $HOME/.nvm/nvm.sh
      nvm install 12.18.3
      nvm use
      npm i -g yarn@1.22.5

ports:
  - port: 3000 # react app
    visibility: public
    onOpen: open-preview
